version: '2'
services:
  web:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5050:5000"
    depends_on:
      - redis
  worker:
    build:
      context: ./flask-celery
      dockerfile: Dockerfile
    environment:
      - LOCAL_USER_ID=1000
    links:
      - vaultproxy:vault
    volumes: 
      - ./keys:/home/node/.ssh
      - ./src:/home/node/src
      - /export/public/cntha-web:/cntha-web
      - /export/public/cntha-web-conf:/cntha-web-conf
      - /export/public/cntha-web-conf-offline:/cntha-web-conf-offline
      - /export/public/cntha-search:/cntha-search
    depends_on:
      - redis
  redis:
    image: redis
  vaultproxy:
    image: nginx
    volumes:
      - ./vault/conf.d:/etc/nginx/conf.d:ro
